FROM gcc:15.2.0 AS build

WORKDIR /root
COPY HelloWorld.c .
RUN gcc -o executable HelloWorld.c 
ENTRYPOINT ["./executable"]

FROM gcc:15.2.0 AS prod
WORKDIR /root
COPY --from=build /root/executable ./executable

ENTRYPOINT ["./executable"]
